### ISSUE TITLE
using jinja2,'Emmett develop' produce the following

### ISSUE THREAD

**Issue by ockan** [emmett-framework/emmett55#3]
using jinja2,when enable async in  jinja2,'Emmett develop' produce the following
![截屏2024-12-23 14 59 23](https://github.com/user-attachments/assets/fef1c35e-dda7-4351-8644-25e09ebaff77)

**Comment by gi0baro** [comment]
This is a Jinja issue, not smth that can be solved in Emmett55.
Also, you should probably use `render_async` in place of `render`.
